[Settings]
ID = "Jean app"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "build/"
  # This will be your default build command
  command = "yarn run build"

  environment = {  NODE_VERSION = "9.11.1", YARN_VERSION = "1.10.1", NPM_VERSION = "5.6.0" }

# Deploy Preview context: All Deploy Previews (https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)
# will inherit these settings.
[context.deploy-preview]
  publish = "build/"
  command = "yarn run build"
# Here is another way to define context specific environment variables
[context.deploy-preview.environment]
  NODE_VERSION = "9.11.1"
  YARN_VERSION = "1.10.1"
  NPM_VERSION = "5.6.0"


[context.production]
  publish = "build/"
  command = "yarn run build"
  environment = {  NODE_VERSION = "9.11.1", YARN_VERSION = "1.10.1", NPM_VERSION = "5.6.0" }

  # COMMENT: This a rule for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

 